# Poller targets (examples). You can also use a single `targets:` list with an `os` field.
linux:
  - host: 192.168.1.10
    username: ubuntu
    password: changeme
    asset_id: null   # optional; if not set, upsert by MAC/name
bsd:
  - host: freebsd.local
    username: root
    password: changeme
    asset_type: server
windows:
  - host: winhost.local
    username: Administrator
    password: "P@ssw0rd"
    domain: CORP             # optional
    winrm_use_ssl: false     # optional, defaults to false
    winrm_transport: ntlm    # optional: ntlm, kerberos, credssp
    applications_limit: 150  # optional cap for installed app inventory
    collect_applications: true   # optional toggle for installed software inventory
api:
  base_url: "http://azre-itassets1.corp.inovagenix.com/api.php"
  api_key: "POLLR_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
interval_seconds: 120
