# Poller targets (examples)
linux:
  - host: 192.168.1.10
    username: ubuntu
    password: changeme
    asset_id: null   # optional; if not set, upsert by MAC/name
windows:
  - host: winhost.local
    username: Administrator
    password: "P@ssw0rd"
api:
  base_url: "http://azre-itassets1.corp.inovagenix.com/api.php"
  api_key: "POLLR_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
interval_seconds: 120
